### PR TITLE
fix(toolbar): increase dropdowns width

### PR DESCRIPTION
**Pull request by JoomFX**
fixes https://github.com/telerik/kendo-themes/issues/3311

### CODE REVIEW

**Review by silviyaboteva — APPROVED** [review]
I'm OK unless the change to 10em was intended for some reason.

**Review by Juveniel — CHANGES_REQUESTED** [review]
@JoomFX by default an input has a [size of 20](https://html.spec.whatwg.org/multipage/input.html#the-size-attribute) which corresponds to the number of characters that a user sees while editing the input. While we cannot use the size attribute in our components, we can set default `width` in the themes that corresponds to that default size (20 characters), which is roughly `10em`.  This is the reason behind the observed change.  

In terms of the proposed change to `12.4em` value - we cannot assume that this width will be sufficient for every component that features a ToolBar, as there are different DropDowns with different character sizes in the components (ImageEditor, FileManager, Pager, etc.) Thus, I believe that a better solution is to increase the width of the pickers in the Editor specifically and not in the ToolBar.

**Comment by JoomFX** [comment]
@Juveniel I'm fine with setting the width in the Editor specifically, however I do believe that doing it in the Toolbar should be fine as well. Especially since the inputs/pickers had this same width (`12.4em`) during all their life and all customers are used to it.
There's no problem at all to add the code in the Editor, I just don't like the idea of adding new code that overrides the code that causes the issue instead of modifying the code that causes the issue.

@joneff @silviyaboteva what do you think?

**Comment by silviyaboteva** [comment]
@Juveniel thank you for clarifying. Now, I remember that we've talked with @joneff about this.

We've made significant changes in the v5 release, so IMO this change is not an issue as we can now say that the default value is a predictable one (20 chars). 

I can suggest in this case to go through the demos of the components and change the widths of the inputs/pickers there for better appearance, and not to change anything from themes.

**Comment by JoomFX** [comment]
@silviyaboteva Well, I don't insist in doing the change in the Toolbar styles, but I do believe that we need to address this issue in the themes.
Please have a look at the issue and the problem we are trying to fix. If we fix the examples only, then the customers will need to add the same custom code to their applications.

**Comment by joneff** [comment]
What @Juveniel said is indeed so -- 20 characters is the default width, which is roughly equal to 10em. For legacy reasons, `12.4em` was transferred blindly from the less to sass themes.

As for the issue we are trying to fix, I understand, but the position stays the same. For the record, in french the width would be vastly insufficient just for the first word which would be "selectionnez / choisir la famille de police"

For "format" we have chosen shorter word e.g. format. I am guessing we do the same for "font family" or "font size". It's a resource after all.

image

That being said, components in toolbars can be sized not only from the themes, but with inline styles. In terms, should a team decides they need a wider box, they can do so by setting inline width. Like @Juveniel 12.4em is not going to be sufficient for all cases, so if a team decides to deviate from our standard (10em) it should do so with caution.

Finally, regarding format dropdown, we can always use non-wraping lines to fit everything.

I am closing this issue.

**Pull request closed without merging**
