### PR TITLE
column-menu: update spacings based on latest design

### PR DESCRIPTION
**Pull request by PreslavKozovski**
part of: https://github.com/telerik/kendo-themes/issues/1971

### CODE REVIEW

**Review by silviyaboteva — APPROVED** [review]

**Comment by inikolova** [comment]
From my testing I observed the following differences with the design:

- [ ]  .k-column-chooser-title, .k-column-list-item -> padding should be the same as .k-columnmenu-item - 4px  (now 2px);

- [ ] Filter -> And/Оr DDL -> margin should be 8px (currently 14px);

- [ ] k-filter-menu .k-actions, .k-filter-menu .k-action-buttons, .k-filter-menu .k-columnmenu-actions -> padding-top should be 4px (now is 14px);

- [ ] .k-filter-menu .k-widget, .k-filter-menu .k-radio-list, .k-filter-menu .k-textbox -> margin should be 8px (currently 7px);

I will add more visual tests so we could handle these cases.

**Comment by PreslavKozovski** [comment]
@inikolova About the first point, I believe that the correct padding is 2px:

image

The space between two items is 4px, so 2px padding for both items is doing the magic.

**Comment by inikolova** [comment]
Adding padding to .k-grid-columnmenu-popup.k-popup makes visible border on the last item in the Angular column menu: 
Screenshot 2020-12-08 at 8 41 07

**Review by inikolova — APPROVED** [review]

**Comment by inikolova** [comment]
The column menu looks great :)

**Review by joneff — APPROVED** [review]

**Pull request merged**
