### PR TITLE
fix(grid): fix broken sticky row styles

### PR DESCRIPTION
**Pull request by epetrow**
Fixes a regression introduced with https://github.com/telerik/kendo-themes/pull/5133

### CODE REVIEW

**Comment by inikolova** [comment]
I think we should remove this row as well, as it is Angular specific -> https://github.com/telerik/kendo-themes/blob/fix-grid-sticky-rows-selection/packages/bootstrap/scss/grid/_theme.scss#L224

**Comment by Juveniel** [comment]
I don't think it is a good idea to return the kendo-grid selectors. Let's discuss this further and search for an alternative.

**Comment by epetrow** [comment]
> I think we should remove this row as well, as it is Angular specific -> https://github.com/telerik/kendo-themes/blob/fix-grid-sticky-rows-selection/packages/bootstrap/scss/grid/_theme.scss#L224
> 
> Also, I think it will be beneficial to add a visual test for covering sticky rows scenario

If we decide to do so due to the current differences in the rendering between the suites we will need to add two tests - one for React locked rows and one for Angular sticky rows

**Comment by silviyaboteva** [comment]
> > I think we should remove this row as well, as it is Angular specific -> https://github.com/telerik/kendo-themes/blob/fix-grid-sticky-rows-selection/packages/bootstrap/scss/grid/_theme.scss#L224
> > Also, I think it will be beneficial to add a visual test for covering sticky rows scenario
> 
> If we decide to do so due to the current differences in the rendering between the suites we will need to add two tests - one for React locked rows and one for Angular sticky rows

Guys, firstly, lets revamp and unify the rendering https://github.com/telerik/kendo-themes-private/issues/283 and after that we can have a single source of truth test.

**Review by silviyaboteva — APPROVED** [review]
The React Grid looks as expected. Demo: https://stackblitz.com/edit/react-dolz78-4nmsyx?file=index.html

The Angular Grid also looks as expected. Demo: https://stackblitz.com/edit/angular-5c56gf-c6xfju?file=src%2Findex.html

**Review by inikolova — APPROVED** [review]

**Pull request merged**
