### PR TITLE
fix: resolve build error due to function in mixin

### PR DESCRIPTION
**Pull request by arpontes**
After the last change, my preprocessor (node-sass) started to break with this message:
"Functions may not be defined within control directives or other mixins"
In fact, this is invalid as we can see in the issue https://github.com/sass/sass/issues/2470.

### CODE REVIEW

**Comment by gyoshev** [comment]
@arpontes Thank you for your contribution! Since this is your first contribution to the project, would you be so kind to sign the [Kendo UI Contribution License Agreement](https://docs.google.com/forms/d/e/1FAIpQLSdSzuLLij8dtytTeiXCzlHcTmHYZIxgrAa7BSaO_fno79ua1A/viewform?c=0&w=1)? It is a legal requirement, since the themes are sometimes shipped with for-profit products.

As a cross-reference this, this PR will resolve https://github.com/telerik/kendo-angular/issues/1387

**Comment by arpontes** [comment]
@gyoshev I've just signed the License Agreement! Thanks!

**Comment by gyoshev** [comment]
@arpontes Excellent, thanks! It seems that our latest build scripts were not contribution-friendly. I've published a [patch](https://github.com/telerik/kendo-themes/commit/ec89ce559ade18c2a214c967e5b876e1cd5b806f) that addresses the issue. Can you please [sync the latest changes from develop](https://help.github.com/articles/syncing-a-fork/#platform-windows) into this branch? While at it, it would be great if you can change the commit message so that it fits the [commit message guidelines](https://github.com/telerik/kendo-themes/blob/develop/CONTRIBUTING.md#-commit-message-guidelines) -- in this case, a `fix: resolve build error due to function in mixin` should do just fine.

**Comment by arpontes** [comment]
@gyoshev , just to confirm, the commit message is the name of the pull request, right? If so, it is done!

**Comment by gyoshev** [comment]
@arpontes I meant the title of the commit:

image

Since this PR includes a single change, I was [able to rewrite the title](https://github.com/telerik/kendo-themes/commit/62821a449faf3dd478dfb2720df770f69616ca81) during a "squash and merge". The same would not be possible if there were several fixes in the branch. You can edit the commit message titles during [an interactive rebase](https://help.github.com/articles/changing-a-commit-message/).

**Comment by arpontes** [comment]
Ok, and thanks for your patience! I'm still learning to use git. :-)

**Comment by gyoshev** [comment]
Don't worry, we've all been there :slightly_smiling_face: Rebasing is a powerful technique that allows you to change the git history. [This article](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) provides a more detailed explanation.

Thanks again for fixing this!

**Pull request merged**
