### PR TITLE
Use `$subtle-text` for upload styling

### PR DESCRIPTION
**Pull request by joneff**
Part of #2234

### CODE REVIEW

**Review by PreslavKozovski — APPROVED** [review]

**Comment by inikolova** [comment]
According to the design, in the Material theme Dropzone padding is 16px -> https://github.com/telerik/kendo-ux/blob/master/themes/material/PNG/upload.png

**Comment by joneff** [comment]
I know, but it's also a toolbar-ish and I am using `$toolbar-padding-*` variables.

**Comment by inikolova** [comment]
Also, the spacing around icon and text in the Dropzone should be 8px, not 4 (Default theme) -> https://github.com/telerik/kendo-ux/blob/master/themes/default/PNG/upload.png

**Comment by inikolova** [comment]
> I know, but it's also a toolbar-ish and I am using `$toolbar-padding-*` variables.

In this case the designs should be updated

**Comment by joneff** [comment]
> In this case the designs should be updated

all designs will be updated to reflect the changes related to colors

**Review by inikolova — APPROVED** [review]

**Pull request merged**
