### PR TITLE
Textarea visual test

### PR DESCRIPTION
**Pull request by epetrow**
Related to: https://github.com/telerik/kendo-themes/issues/3403

### CODE REVIEW

**Comment by silviyaboteva** [comment]
@epetrow can you please check why so many tests are changed. I couldn't see any differences though.
@joneff is this related to the new Firefox version 97.0.1 from February 17, 2022?

**Comment by JoomFX** [comment]
@silviyaboteva Regarding the changed tests - it is because of the image in the tests (mostly Chip, Avatar, etc).
It does seem to be related to the new FF version.

**Comment by Juveniel** [comment]
I can confirm that the issue is related to the new FF version - this can be verified by examining [the build artifacts here](https://github.com/telerik/kendo-themes/runs/5275823925?check_suite_focus=true) where we can see that the last good commit was running version 96.0. When compared to the CI Visual for the current commit, the version is now 97.0.

I have opened [a new PR ](https://github.com/telerik/kendo-themes/pull/3408)to trigger the image tests. We can rebase the currently opened PRs after it is merged.

**Review by silviyaboteva — APPROVED** [review]

**Review by joneff — APPROVED** [review]
I would much prefer if this was done by using an `overflow` attribute with initial `auto` value, but the current solution would also suffice.

**Pull request merged**
