### PR TITLE
fix(input): set correct  border-width for flat inputs and pickers

### PR DESCRIPTION
**Pull request by epetrow**
Closes: https://github.com/telerik/kendo-themes/issues/3601

### CODE REVIEW

**Comment by TeyaVes** [comment]
My only concern here is that the inputs and pickers in flat mode become shorter and there would be a slight vertical misplacement with 1px if positioned next to a button for example. However, I am not sure if this would be a serious issue

**Comment by epetrow** [comment]
> My only concern here is that the inputs and pickers in flat mode become shorter and there would be a slight vertical misplacement with 1px if positioned next to a button for example. However, I am not sure if this would be a serious issue

I don't think there is a noticeable difference, but I might be mistaken.

image

image

**Review by joneff — CHANGES_REQUESTED** [review]
This will make flat inputs a tad smaller. Please think of a different approach.

**Comment by epetrow** [comment]
Closing this for now since there is no obvious fix. We'll revisit this in the future.

**Pull request closed without merging**
