### PR TITLE
Signature updates

### PR DESCRIPTION
**Pull request by epetrow**
Based on changes in the design files:

- Default: https://www.figma.com/file/gWUIux95BHxemqWwOw9ZwB/Default-Theme---Internal-Usage?node-id=4833%3A140758
- Bootstrap: https://www.figma.com/file/k8eCVo9JZeHZlV9o8SXZtd/Bootstrap-Theme---Internal-Usage?node-id=1848%3A104815
- Material:  https://www.figma.com/file/qpaRti273eNVEEOYOUxojT/Material-Theme---Internal-Usage?node-id=1577%3A96283

### CODE REVIEW

**Review by Juveniel — APPROVED** [review]

**Review by TeyaVes — APPROVED** [review]

**Comment by Juveniel** [comment]
Waiting for final review from @ag-petrov before merging this

**Review by ag-petrov — APPROVED** [review]

**Comment by ag-petrov** [comment]
Tested the component looks good, we just need to clarify how rounded full will behave. @epetrow will contact the design team in regards of this.

**Comment by epetrow** [comment]
> Tested the component looks good, we just need to clarify how rounded full will behave. @epetrow will contact the design team in regards of this.

After a discussion with @dmanova we decided that the signature component should not implement rounded full as it does not look good.

**Comment by Juveniel** [comment]
@epetrow  change all commits to `chore:` as the Signature component is not yet released.

**Pull request merged**
