### PR TITLE
Vertical stepper

### PR DESCRIPTION
**Pull request by epetrow**
Fixes: https://github.com/telerik/kendo-themes/issues/2723

Needs changes in the inline styles set via the component. Please check the visual test for reference:
 - [x] Kendo UI for jQuery //cc @veselints 
 - [ ] Kendo UI for Angular
 - [x] KendoReact (https://github.com/telerik/kendo-react-private/pull/1663)
 - [ ] Kendo UI for Vue //cc @zdravkov 
 - [X] Telerik Blazor @KristianMariyanov (https://github.com/telerik/blazor/pull/3870)

### CODE REVIEW

**Review by silviyaboteva — APPROVED** [review]
🎉

**Comment by veselints** [comment]
@epetrow 
The following style:
```css
.k-progressbar-vertical {
            position: absolute;
            top: calc(#{$stepper-indicator-height} / 2);
}
```

Will destroy the positioning of the progressbar element in jQuery.:
https://dojo.telerik.com/IheWoZuc/4

The `top: ...` style should be supplied to the element as an inline style, just like all the `display: grid` styling is done. The jQuery Stepper uses mutch simpler element calculation logic, which does not include `display: grid`. Hence, any styling relevant to that case should be kept inline.

**Review by veselints — CHANGES_REQUESTED** [review]
The following style:
```css
.k-progressbar-vertical {
            position: absolute;
            top: calc(#{$stepper-indicator-height} / 2);
}
```

Will destroy the positioning of the progressbar element in jQuery.:
https://dojo.telerik.com/IheWoZuc/4

The `top: ...` style should be supplied to the element as an inline style, just like all the `display: grid` styling is done. The jQuery Stepper uses mutch simpler element calculation logic, which does not include `display: grid`. Hence, any styling relevant to that case should be kept inline.

**Comment by epetrow** [comment]
@veselints Thank you for the input, in that case there is no need for any changes in the JQuery widget.

**Review by veselints — APPROVED** [review]

**Review by KristianMariyanov — APPROVED** [review]

**Review by joneff — APPROVED** [review]

**Pull request merged**
