### PR TITLE
fix(input): update input display property

### PR DESCRIPTION
**Pull request by inikolova**
Fixes https://github.com/telerik/kendo-themes/issues/785

### CODE REVIEW

**Comment by PreslavKozovski** [comment]
Another possible solution is to target IE like this:
```
.k-ie11 {
    .k-textbox,
    .k-input.k-textbox,
    .k-textarea {
        ...
    }
}
```

What do you think about this?

**Comment by inikolova** [comment]
@PreslavKozovski, this will not work with the Kendo UI for Angular components

**Comment by PreslavKozovski** [comment]
@inikolova 
As far as I know, such classes can be added to our Angular components. For example - 

image

Having said that, during our next meeting, we can discuss what we are going to do with such cases. Do we want to scope IE styles, or are we going to implement styles that can work in all supported browsers?

**Comment by joneff** [comment]
@PreslavKozovski my bad. I didn't explain the task properly. The behaviour in question was caused by IE not understanding input { display: inline-flex } properly. To target this, it needs to be inline-flex.

Since input.k-textbox and textarea.k-textarea cannot have child elements, we can safely have:

```scss
input.k-textbox,
textarea.k-textarea {
    display: inline-block
}
```

without affecting any browser :)

**Pull request merged**
