### PR TITLE
fix(dropdownlist): keep the height of empty dropdownlist

### PR DESCRIPTION
**Pull request by silviyaboteva**
Fixes https://github.com/telerik/kendo-themes/issues/5046

TODO
- [x] we should ping all teams to update the rendering accordingly (by removing the `k-input-value-text` element if there is no value set.

### CODE REVIEW

**Comment by epetrow** [comment]
In my opinion this might not be the best way to handle the issue. I think the problem here stems from the `padding-block` value which we apply to `k-input-button`. For all themes except for Material this value matches the one applied through the sizing classes of the button. 

This causes the Dropdownlist button in Material to be shorter which becomes noticeable when `k-input-value-text` is not rendered or when there is no placeholder.

There also seems to be a difference in the rendering  -- currently in the spec of the Dropdownlist `k-input-value-text` is not rendered if there is no value, but in some suites ( Angular for [example](https://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/) ) is present event if there is no placeholder or value.

So we should maybe decide:

- do we always render `k-input-value-text` and correct the component spec
- conform to the [design](https://www.figma.com/design/Bun5XXsG0UuzCMz5GyDoHK/Telerik-%26-KENDO-UI-Kit-3.0-for-Material?m=auto&node-id=593-13371) where only the inline padding of the Dropdownlist button seems to be adjusted

Another thing unrelated to the aforementioned, when updating existing or adding new tests, please do so in `packages/html/src/${component-name}/tests`

**Comment by silviyaboteva** [comment]
Thank you @epetrow, I will research for the `pdding-block` solution and apply it instead.

As for the `k-input-value-text` element, I think, it's up to @telerik/kendo-front-end to decide if we have to render it in case no placeholder, nor value is provided. I also checked the Angular and Blazor suites and noticed that there is always rendered, but is this semantically correct? The KendoReact team based on the test that showcase the placeholder without this `k-input-value-text` element. And we also use this rendering in the adaptive DropdownTree and grid filter row tests.

I'll update the `packages/html/src/${component-name}/tests` as well. Thanks!

**Comment by silviyaboteva** [comment]
I double checked [the spec of the DropdownList](https://github.com/telerik/kendo-themes/blob/develop/packages/html/src/dropdownlist/dropdownlist.spec.tsx#L114) and the `k-input-value-text` element is rendered only if there is a value. For reference: https://github.com/telerik/kendo-themes/blob/develop/packages/html/src/input/input-inner-span.tsx#L38. 

So, in this case the fix with the `padding-block` is required in Material theme :)

**Comment by silviyaboteva** [comment]
Based on the comments from the team, I updated the value of the `button-padding-y` to `null`, so the correct padding is set `padding-block` of the `k-input-inner` element.

I also add tests with no placeholder nor value to all inputs, dropdowns and pickers, and for their fill modes.

**Review by inikolova — APPROVED** [review]

**Pull request merged**
