### PR TITLE
apply correct color for the today link

### PR DESCRIPTION
**Pull request by PreslavKozovski**
part of #254

### CODE REVIEW

**Comment by joneff** [comment]
@elena-gancheva  there was an issue with the image tests and the screenshots were not correctly sized

**Comment by joneff** [comment]
@lkarakoleva can you take a look at this? If I recall correctly, pink was the correct color, but the designs are not yet updated.

P.S.
Do not merge yet

**Comment by lkarakoleva** [comment]
Link color is the correct color, which is pink. I update the designs:
https://github.com/telerik/kendo-ux/blob/master/themes/material/calendar-jquery.psd

**Comment by PreslavKozovski** [comment]
Thanks, I am closing this PR.

**Pull request closed without merging**
