### PR TITLE
Grid sorting indicator

### PR DESCRIPTION
**Pull request by inikolova**
Discussion: https://github.com/telerik/k2/issues/280

Part of: https://github.com/telerik/kendo-themes/issues/410

### CODE REVIEW

**Review by PreslavKozovski — APPROVED** [review]
The changes LGTM. However, you could order the properties as described here - https://github.com/telerik/kendo-themes/wiki/Code-Styleguide#declaration-order

**Review by joneff — APPROVED** [review]
I see only two minor things:

* order of props
* alignment of k-cell-inner: do we need space between the items?

those are minor, so we can go forth with the merge

**Review by silviyaboteva — APPROVED** [review]
In React Grid, we have not planned to change the rendering yet, but I tested and the new styles don't break the current layout.

**Review by PreslavKozovski — CHANGES_REQUESTED** [review]
These styles are not going to work in an RTL scenario.

**Review by PreslavKozovski — APPROVED** [review]

**Review by joneff — APPROVED** [review]

**Pull request merged**
