### PR TITLE
fix(input): excess text is not properly cut

### PR DESCRIPTION
**Pull request by JoomFX**
fixes https://github.com/telerik/kendo-themes/issues/3263

### CODE REVIEW

**Review by joneff — CHANGES_REQUESTED** [review]
Examine the screenshots. In certain cases, like in the colorpicker and responisve pager, we need overflow clip.

Consult with @Juveniel about image editor and spreadsheet. Consult with @silviyaboteva about pivotgrid.

**Comment by JoomFX** [comment]
We discussed the situation with @ivelina-penkova and the suggestion is to use `ellipsis` as a default and then go through each and every case/component and determine how the particular scenario should be handled (be it using `clip`, increasing the width of the input/picker, etc).

Here is a list of the problematic scenarios
-  ["Pixels" picker in the Image Editor](https://github.com/telerik/kendo-themes/pull/3314/commits/6c606e730707efb767d999997e1ee284717454a0#diff-44c0b33b256e7c14826b0b1ece1b1a90c67709fd79e83e4d020bbc9efb5b7946)
- [The "Items per page" picker in the Responsive Pager](https://github.com/telerik/kendo-themes/pull/3314/commits/6c606e730707efb767d999997e1ee284717454a0#diff-ad1deb855f8aa4962ebf7a391fe25299d19b974a07e15fba45bda2112f2a4064)
- The pickers in the Pivotgrid settings panel ([horizontal](https://github.com/telerik/kendo-themes/pull/3314/commits/6c606e730707efb767d999997e1ee284717454a0#diff-488a76bca236405378fb907e28e71a3390a96ec057233a5767b8b6841052bdc2) and [vertical](https://github.com/telerik/kendo-themes/pull/3314/commits/6c606e730707efb767d999997e1ee284717454a0#diff-5ebd937c5963ae2384f657fa4c5039b8655e8f6837f75c221e67c34df1be232c))
- [The font picker in the Spreadsheet](https://github.com/telerik/kendo-themes/pull/3314/commits/6c606e730707efb767d999997e1ee284717454a0#diff-c4cf42f62f958c31ea0e1ae4c3b7ec77fb003be44f4d932bc1dc43395fe5cfcb)
- [The inputs in the ColorGradient](https://github.com/telerik/kendo-themes/pull/3314/commits/6c606e730707efb767d999997e1ee284717454a0#diff-fcd24eb2f2dac0d0be801bffc3b70e5d53f27a5e4e25662680f53d71e48a6d87)

**Comment by epetrow** [comment]
Additionally, could you also check if here we need to add ellipsis or if it should stay as is https://github.com/telerik/kendo-themes/issues/2784

**Comment by JoomFX** [comment]
After another discussion with @ivelina-penkova and @joneff here's how we will handle the problematic cases:

1. **"Pixels" picker in the Image Editor** (imageeditor-resize-pane.html) - the pickers should be `text-overflow: clip;`. Furthermore, a discussion should be raised whether the default text in the pickers should be "Pixels" or "Px". 
2. **The "Items per page" picker in the Responsive Pager** (pager-responsive.html) - the pickers should be `text-overflow: clip;`. 
3. **The pickers in the Pivotgrid settings panel** (pivotgrid-settings-panel-horizontal.html) - it doesn't seem to be implemented in any of the suites. It is present in the visual tests only therefore we are leaving it for now.
4. **The font picker in the Spreadsheet** (spreadsheet.html) - increase the inputs/pickers width to 10em (remove the spreadsheet override and leave the width that comes from the toolbar).
5. **The inputs in the ColorGradient** (colorpicker-dropdown.html) - the inputs should be `text-overflow: clip;`. Furthermore, a discussion should be raised whether the container (and the inputs) width should be increased.

@epetrow Whenever and wherever it is a case of localization, it should be `text-overflow: ellipsis;`

**Review by joneff — APPROVED** [review]

**Pull request merged**
