### PR TITLE
test(floating-label): add examples for focus, hover, disabled and inv…

### PR DESCRIPTION
**Pull request by epetrow**
…alid state

Closes: https://github.com/telerik/kendo-themes/issues/3412

### CODE REVIEW

**Comment by tsvetomir** [comment]
Please consider organizing these tests under `tests/visual/src`. This will make it easier for product teams to add markup snapshots for regression testing.

**Review by silviyaboteva — APPROVED** [review]

**Review by joneff — APPROVED** [review]

**Comment by Stamo-Gochev** [comment]
Any reason we decided to drop the "red" text color of the label when its associated input is invalid?

Here is the result from the updated [rendering](https://github.com/telerik/kendo-themes/blob/9c6ffad73cdf1aeca831c602b6d3150aa50bfdb0/tests/visual/src/misc/floating-label.html#L159-L183):
image

There seems to be some variance over this, but when using the label with form field component, it has red text when the value is invalid in ng2:
https://www.telerik.com/kendo-angular-ui/components/forms/forms-guideline/#toc-floating-labels
image

A similar thing happens in react:
https://www.telerik.com/kendo-react-ui/components/inputs/input/forms/#toc-setting-validation-requirements
https://www.telerik.com/kendo-react-ui/components/inputs/numerictextbox/forms/#toc-enforcing-the-validity-state

This is also the case with the blazor [Form](https://demos.telerik.com/blazor-ui/form/validation):
image

This makes me think we are more leaning towards red label text when the input is invalid.

**Comment by Stamo-Gochev** [comment]
Any thoguths on https://github.com/telerik/kendo-themes/pull/3438#issuecomment-1066444797? /cc @telerik/kendo-front-end

**Comment by epetrow** [comment]
The "red" text color is applied to the label only when it is used within a form field: `k-form-error, .k-text-error, .k-form-field-error .k-label { @include fill( $color: $error ); }`

Regarding the second question, this is expected and both classes produce the same behavior.

@Juveniel please, correct me if I am wrong

**Pull request merged**
