### PR TITLE
feat(utils): add font-size utils

### PR DESCRIPTION
**Pull request by JoomFX**

### CODE REVIEW

**Review by PreslavKozovski — CHANGES_REQUESTED** [review]
Add these classes to all themes.

**Comment by JoomFX** [comment]
The other themes import the default theme. Here they are:

[Bootstrap](https://github.com/telerik/kendo-themes/blob/develop/packages/bootstrap/scss/utils/_text.scss)
[Material](https://github.com/telerik/kendo-themes/blob/develop/packages/material/scss/utils/_text.scss)
[Classic](https://github.com/telerik/kendo-themes/blob/develop/packages/classic/scss/utils/_text.scss)

**Review by PreslavKozovski — APPROVED** [review]
my bad :)

**Review by joneff — CHANGES_REQUESTED** [review]
I think we should go with `k-fs-*`. The same way we do with margin / padding -- https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/utils/_spacing.scss

**Review by inikolova — APPROVED** [review]

**Review by joneff — APPROVED** [review]

**Pull request merged**
