### PR TITLE
Upload unified rendering improvements

### PR DESCRIPTION
**Pull request by magdalenaan**
related https://github.com/telerik/kendo-themes/pull/4076/commits

Simplify the new Upload rendering as the following:
- remove `.k-file-single` and `.k-file-multiple` wrappers
- add the `.k-file-multiple` class to the `.k-file` element

### CODE REVIEW

**Comment by Juveniel** [comment]
Let's wait for @TeyaVes review here. We cannot merge this prior to R1 release, as it's just a couple of working days before the code freeze.

**Comment by TeyaVes** [comment]
Looks good to me. I'm just wondering whether we should keep the k-file-single class added to k-file so that it can be targetted easily. Also, the JSON needs to be updated as well.

**Comment by magdalenaan** [comment]
I discussed the case with the dev and manager of the Angular team and they are OK with removing the DOM element. The `kendo-upload-file-list-single-item` and `kendo-upload-file-list-multiple-items` Angular components will be moved to their parent \<li>. The Angular team can make such updates after the official R1 release.


>  I'm just wondering whether we should keep the k-file-single class added to k-file so that it can be targetted easily. Also, the JSON needs to be updated.

I am not sure if this is necessary as the only reason for keeping the `k-file-multiple` class is one CSS rule for [vertical alignment](https://github.com/telerik/kendo-themes/pull/4184/files#diff-dfb8e081fe71a490159169cb0cbb4939e670c430f8b972b0f6daa45daf06011fR95).

> Also, the JSON needs to be updated.

I have updated the JSON.

**Comment by Juveniel** [comment]
This should not be merged prior to R1, thus marking it as draft for the time being.

**Comment by Juveniel** [comment]
After a discussion in the FE team, we decided not to pursue this change at the moment, as the only benefit that will come out of this is removing one of the elements that we use to wrap the files container. Thus, the cost of updating this in all products is currently not worth pursuing. 

@dtopalov you can also close the related PR in Angular as well.

**Pull request closed without merging**
