### PR TITLE
Color System Material

### PR DESCRIPTION
**Pull request by JoomFX**
**DO NOT MERGE**

related to https://github.com/telerik/kendo-themes/pull/4718

NOTE:
----------
1. ~~Button Disabled State (and Disabled State in general) does not look perfect. We might want to consider introducing dedicated `$kendo-disabled-*` variables.~~ - **FIXED**
2. ~~Progressbar/Stepper/etc does not look perfect (the background color is too pale). We might want to darken the `primary-subtle` color.~~ **FIXED: After a discussion with the design team, the `primary-subtle` colors were darkened.**
3. The design of the Grid Row States is changed on purpose. This is [the new design](https://www.figma.com/file/JPVKllqWHaXbKa4GmPDHdd/Color-Names?node-id=505%3A69258&mode=dev) suggested by the design team. Since the Selected Row design is no longer grayish (it now uses the primary color as in all other themes), the changes in the code aim to make the styles consistent across all themes by removing some of the overrides and inheriting those styles from the Default theme. Here's a quick summer on how the Grid Row States styles work - the `hover` styles are applied on the Row, while the `selected` styles are applied on the Cell. That's how we achieve the overlaying effect of two different colors. Furthermore, only in Material (since only here the `focus` style is a background color instead of box shadow), we apply the `focus` style on the after element so the different layers can overlay over each other.

### CODE REVIEW

**Comment by inikolova** [comment]
Please find my observations below - maybe some of them are expected, however please take a look:
- [ ] - Calendar, List items - hover, focus, selected states are darker;
- [ ] - Disabled text color is darker
- [ ] BottomNav - focused item - background is too dark
- [ ] Breadcrumb - selected item background is darker
- [ ] ButtonGroup - disabled text color is darker and on dark background is not visible - (tests/_output/material/button-group/button-group.png)
- [ ] Button - outline - disabed text color is too dark; solid button - disabled background is lighter; Success / error solid buttons text color is white now; Primary solid button - active and selected states are now darker
- [ ] Calendar - selected range is too pale
- [ ] Chip - outline - hover, focus, selected background is darker. Same for success, warning, error and info colors
- [ ] Combobox, DateInput, etc. - flat, solid and outline - disabled text color is darker
- [ ] List - hover, focus, selected are darker
- [ ] Editor - text highlight is too pale; Table wizard - selected cells - missing borders
- [ ] FAB - focus - background is darker; Disabled text is too dark; FAB - background is darker for all colors - tests/_output/material/fab/fab-states.png
- [ ] Filemanager - file background is darker
- [ ] Filemanager - Gridview -> Splitter border is too pale and is not visible
- [ ] Form - slider track is almost invisible

**Comment by zhpenkov** [comment]
Material:

- bottom-nav-flat:

- [ ] the selected element color of the secondary theme is black (was secondary color).

- [ ] the selected element color of the light theme is darker.

_[img1](https://raw.githubusercontent.com/telerik/kendo-themes/568825fb5302ae17c2be38f7c1698d9ef13c076a/tests/_output/material/bottom-nav/bottom-nav-flat.png) -> [img2](https://raw.githubusercontent.com/telerik/kendo-themes/23e2c6c21fddbe3f68e56ea04398967431906f71/tests/_output/material/bottom-nav/bottom-nav-flat.png)_

- button-group

- [ ] disabled state text colors and border differ

[img1](https://raw.githubusercontent.com/telerik/kendo-themes/23e2c6c21fddbe3f68e56ea04398967431906f71/tests/_output/material/button-group/button-group.png) -> [img2](https://raw.githubusercontent.com/telerik/kendo-themes/568825fb5302ae17c2be38f7c1698d9ef13c076a/tests/_output/material/button-group/button-group.png)

- card

- [ ] primary color too pale

- [ ] card texts as a whole are a little bit too dark (especially on the vivid colors).

[img1](https://raw.githubusercontent.com/telerik/kendo-themes/23e2c6c21fddbe3f68e56ea04398967431906f71/tests/_output/material/card/card-variants.png) -> [img2](https://raw.githubusercontent.com/telerik/kendo-themes/568825fb5302ae17c2be38f7c1698d9ef13c076a/tests/_output/material/card/card-variants.png)

- dock-manager-navigator

- [ ] hover seems darker


https://raw.githubusercontent.com/telerik/kendo-themes/23e2c6c21fddbe3f68e56ea04398967431906f71/tests/_output/material/dock-manager/dock-navigator.png

https://raw.githubusercontent.com/telerik/kendo-themes/568825fb5302ae17c2be38f7c1698d9ef13c076a/tests/_output/material/dock-manager/dock-navigator.png

~

dropdownlist

hover, focus item states seem darker

https://raw.githubusercontent.com/telerik/kendo-themes/23e2c6c21fddbe3f68e56ea04398967431906f71/tests/_output/material/dropdownlist/dropdownlist-option-label.png

https://raw.githubusercontent.com/telerik/kendo-themes/568825fb5302ae17c2be38f7c1698d9ef13c076a/tests/_output/material/dropdownlist/dropdownlist-option-label.png

~

**Comment by zhpenkov** [comment]
My additional observations.

 - [ ] ButtonGroup > disabled solid on gray bg - becomes gray now
[img1](https://raw.githubusercontent.com/telerik/kendo-themes/4426cbde8b4d1a6bad8703f5bd8c18d86f4ecc16/tests/_output/material/button-group/button-group.png) -> [img2](https://raw.githubusercontent.com/telerik/kendo-themes/b255d22b2c2c172461f14e01890fae246f614673/tests/_output/material/button-group/button-group.png)

 - [ ] Button > light theme > outline - significantly more dark
[img1](https://raw.githubusercontent.com/telerik/kendo-themes/4426cbde8b4d1a6bad8703f5bd8c18d86f4ecc16/tests/_output/material/button/button-outline.png) -> [img2](https://raw.githubusercontent.com/telerik/kendo-themes/b255d22b2c2c172461f14e01890fae246f614673/tests/_output/material/button/button-outline.png)

 - [ ] Calendar> range hovered td/day - different color 
 (at 3rd calendar)
 [img1](https://raw.githubusercontent.com/telerik/kendo-themes/4426cbde8b4d1a6bad8703f5bd8c18d86f4ecc16/tests/_output/material/calendar/calendar-classic-jquery.png) -> [img2](https://raw.githubusercontent.com/telerik/kendo-themes/b255d22b2c2c172461f14e01890fae246f614673/tests/_output/material/calendar/calendar-classic-jquery.png)

  - [ ] MediaPlayer > title shadow - lighter
[img1](https://raw.githubusercontent.com/telerik/kendo-themes/4426cbde8b4d1a6bad8703f5bd8c18d86f4ecc16/tests/_output/material/mediaplayer/mediaplayer.png) -> [img2](https://raw.githubusercontent.com/telerik/kendo-themes/b255d22b2c2c172461f14e01890fae246f614673/tests/_output/material/mediaplayer/mediaplayer.png)

**Comment by epetrow** [comment]
These are some additional things that I noticed:

## ActionSheet
- [ ] list item focus and hover state look the same
- [ ] disabled action and action description color are different

## BottomNav
- [ ] light theme color selected state looks too pale

## Outline Button
- [ ] light, dark and inverse theme colors look the same

## Gant
- [ ] selected sticky row state is different

## Grid
- [ ] focus state has changed across all tests

## ListView
- [ ] focus, selected, focus selected item states look the same

**Pull request closed without merging**
