### PR TITLE
Fixed invalid syntax on compound selector

### PR DESCRIPTION
**Pull request by blemaire**

### CODE REVIEW

**Comment by joneff** [comment]
@blemaire consider the following snippet:

```scss
// input
.button { color: red; }
.flat { color: blue; }
.button.flat {  color: green; }

.compound { @extend .button.flat; }

// output
.button { color: red; }
.flat { color: blue; }
.button.flat, .compound { color: green;}
```
Which is precisely what we want to achieve.

Simply changing the selectors will make the code compile but will not yield the same result. A much more thorough refactoring is required and we are considering it for a later stage. Probably when we drop older versions of angular. The said refactoring will be a breaking change so we'll aptly bump the major version as well.

We are aware of the issue with dartsass (#641) and for now we stick to compiling with libsass.

/cc @Bjego, @cluetjen

**Comment by blemaire** [comment]
I understand how this PR does not yield the same result, could we come up with a solution involving [Extend/inheritance](https://sass-lang.com/guide#topic-7) for now.

this place is a good candidate to fix most of the compound selectors: [kendo-theme-default-button]5https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/button/_layout.scss#L206)

A `%k-button__k-flat' selector could be added and then used in the places that currently use `.k-button.k-flat` as a compound selector: so `@extend .k-button.k-flat;` would become `@extend %k-button__k-flat;`

**Comment by joneff** [comment]
That might patch things up for now, yes. Of course we need to add a patch for `.k-button.k-primary.k-flat` as well. There are some 175 imports, mostly `.k-button.k-flat`, but we should check them all.

Also, I am not quite keen on BEM style syntax, as we don't have it anywhere else.

Lastly, patching things up, while solving the compiling issue, does not solve the bigger issue, namely how do we deal with difference in behaviour and should we consider updating our modifier strategy, say `.k-button-primary` instead of `.k-button.k-primary` to sort of future proof for this particular behaviour.

**Comment by blemaire** [comment]
Ahah, the name was just an example, I'm only getting started with kendo so not quite used to naming conventions. I did not realise there was that many compound selectors, sounds like hell to migrate 😢 
Closing this fornow, let's carry on on the related issue #641

**Pull request closed without merging**
