### PR TITLE
Successfully publish nugets

### PR DESCRIPTION
**Pull request by joneff**
We needed just a bit of tweaking, but it's ready: https://github.com/orgs/telerik/packages?repo_name=kendo-themes. It's worth noting that the currently released packages are not production ready yet, because we haven't really tested them. I am, however, confident that we'll be able to make them production ready in time for PI2.

@telerik/blazor-team if need be, we can publish to any nuget feed, since the `nuget-push` script accepts parameters.

### CODE REVIEW

**Review by Juveniel — APPROVED** [review]
lgtm

**Comment by matanasov** [comment]
The nuget package doesn't contain any css files. It has only scss files. We need to have the theme all.css file as well as all swatch .css files in the package:
https://www.screencast.com/t/Pwau4v6Slxyw

**Comment by joneff** [comment]
@matanasov https://github.com/telerik/kendo-themes/packages/1680584 appears everything is working correctly

**Comment by Stamo-Gochev** [comment]
The nuget package contains CSS files indeed, they are just in a specific folder:
image

We need to check if they can be read from the path `contentFiles/any/any/wwwroot/css` or we need to use something like `contentFiles/wwwroot/css` or even `/wwwroot` for Blazor.

**Comment by matanasov** [comment]
The package seems to install correctly and .css files are now distributed. However they are added to the project as links and are not served from the project folder, but from the .nuget cache folder. Compare the normal .css file location compared to the themes .css file location bellow:

image

**Pull request merged**
