### PR TITLE
fix(tilelayout): hide the header of an overlapped item

### PR DESCRIPTION
**Pull request by silviyaboteva**
Resolves https://github.com/telerik/kendo-themes/issues/2245

### CODE REVIEW

**Review by PreslavKozovski — CHANGES_REQUESTED** [review]
You can add a test for this scenario. However, on a side note, the Angular implementation of the TileLayout is wrong. We should not allow the usage of specific grid-area possitions. We use the "order" property of this.

Having said that, if the JS implementations were correct, this scenario would not be possible to achieve.

**Review by JoomFX — APPROVED** [review]
Apart from Presli's comment, it looks good to me.

@PreslavKozovski The StackBlitz example shows the React TileLayout, not Angular.
Is this the implementation you are talking about?

**Comment by silviyaboteva** [comment]
@PreslavKozovski we also have order property applied by default to each of the tiles. However, the case is hit when 2 tiles have the same `row` applied. In this case, both Tile 4 and Tile 1 are on the third row, and the first spans 3 columns.

If the `row` prop is not applied, this case cannot be met, as the Tile will move to the next available row.

**Review by joneff — APPROVED** [review]

**Comment by joneff** [comment]
Just to clarify: while a css grid "cell" may indeed have order, start, end and span, setting all those will result inevitably in overlapping! That's the idea of the css grid -- that you can do that!

So each suite is doing their part to avoid said overlapping:
* in kendo-jquery, there is no specific row / col index. instead there is order and size (span)
* in kendo-react, we are using an external library 

I am not sure about kendo-angular, but I tested with explicit overlapping boxes and it's possible to overlap them initially.

**Pull request merged**
