### PR TITLE
Progressbar rtl

### PR DESCRIPTION
**Pull request by PreslavKozovski**
fixes: #310

### CODE REVIEW

**Comment by gyoshev** [comment]
The Material Guidelines have a nice document for [implementing RTL support](https://material.io/design/usability/bidirectionality.html). Progress bars fall under the "passage of time" section, and shouldn't be reversed.

**Comment by PreslavKozovski** [comment]
Are we going to follow these guidelines for the other SASS themes? 

If yes, should we remove the "RTL" styles from the LESS themes? By doing this, we will be consistent, however, it will cause a breaking change.

**Comment by joneff** [comment]
If I may, can't we just flip the proggress bar for rtl? And then in media player flip it back?

Actually, if we decide yo use flexbox entirely, we may getaway with having to provide the logic for the various mods entirely

**Comment by joneff** [comment]
If you add `dir="rtl"` to this example what it does is flipping, actually rotating 180 degrees:

```css
.mat-progress-bar[dir=rtl],
[dir=rtl] .mat-progress-bar {
    transform: rotateY(180deg);
}
```

Source: https://github.com/angular/material2/blob/8ed0129906874b9c452a6fb5495b12a5cd18110b/src/lib/progress-bar/progress-bar.scss#L77.

So I guess it's quite a legit solution to simply flip when in RTL

**Pull request merged**
