### PR TITLE
Chat quick replies focus

### PR DESCRIPTION
**Pull request by silviyaboteva**
Part of https://github.com/telerik/kendo-react-private/issues/2321
Resolves also: https://github.com/telerik/web-components-ux/issues/747

Synced with the design team: https://github.com/telerik/kendo-react-private/issues/2321#issuecomment-2220447431

> ### Important note
> I have excluded the quick reply element from the contrast test due to the fact that it was failing focus indicator contrast ratio requirement. I did that as the quick reply has the same styling as the outline button which is also an excluded element.

### CODE REVIEW

**Comment by Juveniel** [comment]
@silviyaboteva the a11y checks for the focus state are failing. We need to ensure that the contrast meets AA for the `default-ocean-blue-a11y` swatch that is tested by the build.

**Comment by silviyaboteva** [comment]
Hey @Juveniel,
I build the swatches and test the mentioned swatch: http://localhost:3000/tests/chat/chat-content.html?theme=default&swatch=default-ocean-blue-a11y

Butt I cannot see any contrast issues. Can you help me debug it?

**Comment by epetrow** [comment]
Also another important thing, when adding a new or editing an existing test **do not** edit the html in the test folder. Any updates or additions to the test need to be made in [packages/html/src](https://github.com/telerik/kendo-themes/tree/develop/packages/html/src) and in the appropriate component folder.

**Review by epetrow — APPROVED** [review]
LG!

**Review by inikolova — APPROVED** [review]

**Comment by silviyaboteva** [comment]
@zhpenkov This can be further discussed within the team and updated later, right? :)

I will move forward and merge this PR in develop

**Pull request merged**
